#!/usr/bin/env python3
import random

def key_gen():
    """Generate dictionary of key that is going to be used for substitution"""
    key={}
    char_list=[]
    char_sub=[]
    #Generate list of capitalized alphabet
    for n in range(65,91):
        char_list.append(chr(n))
        char_sub.append(chr(n))

    #Shuffle the subtitution list to create randomness
    random.shuffle(char_sub)
    
    plain_key=""
    #Add the character and its' subtition to the key dictionary
    for c, c_sub in zip(char_list,char_sub):
        plain_key+=c_sub
        key[c]=c_sub
        key[c.lower()]=c_sub.lower()
    return key,plain_key

def encrypt(key,message):
    """Encrypt/Decrypt the message using the generated key"""
    cipher=""
    for letter in message:
        #If the letter in the message are in the key dictionary -> replace it
        if letter in key:
            cipher+=key[letter]
        #Else keep it as it is
        else:
            cipher+=letter
    return cipher

def dkey_gen(key):
    """Generate decryption key based on an ordered substitution string"""
    dkey={}
    alphabet=[]
    #Generate ordered alphabet
    for n in range(65,91):
        alphabet.append(chr(n))
    
    #Using the substition string to generate a decryption key
    for c, c_sub in zip(alphabet,key):
        dkey[c_sub]=c
        dkey[c_sub.lower()]=c.lower()
    return dkey

def main():
    """Accept user message and encrypt it using generated key"""
    print("#################################")
    print("Welcome to subtitution cipher")
    print("1. Encrypt a message")
    print("2. Decrypt a cipher text")
    print("#################################")
    choice=input("Enter your choice: ")
    if choice == "1":
        message=input("Enter your message: ")
        #Generate encryption key and encrypt the message
        key,plain_key=key_gen()
        cipher=encrypt(key,message)
        print("[+] Your key (use to decrypt): {}".format(plain_key))
        print("[+] Your encrypted message is: {}".format(cipher))
    elif choice == "2":
        cipher=input("Enter your cipher text: ")
        key=input("Enter your key string (generated by the program): ")
        #Generate the decryption key and decrypt the cipher text
        dkey=dkey_gen(key)
        message=encrypt(dkey,cipher)
        print("[+] Decrypted message: {}".format(message))
    else:
        print("[-] Error! Invalid option")

if __name__ == "__main__":
    main()
